=== AlainWafflard/4IPW3/syllabus/25_intégration_XML/library.dtd
<!ELEMENT biblio (livre*)>

<!ELEMENT livre (titre, auteur+, nb_tomes?, couverture?)>
  <!ATTLIST livre
	livre_id ID #REQUIRED
    type (roman | nouvelles | poemes | théâtre) #IMPLIED
    lang CDATA "fr"
  >

<!ELEMENT titre (#PCDATA)>

<!ELEMENT auteur (#PCDATA)>  
  <!ATTLIST auteur
    country (BE | FR | US | GB | NL) 'FR'
  >

<!ELEMENT nb_tomes (#PCDATA)>
  <!ATTLIST nb_tomes
    value CDATA "1"
  >

=== AlainWafflard/4IPW3/syllabus/25_intégration_NoSQL/library+dtd+xsl.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE biblio SYSTEM "library.dtd">
<!-- 
	Au choix, on applique le CSS ou le XSL, 
	mais le résultat est bien entendu assez différent.
	Le XSL est plus riche que le CSS. 
	Commentez l'un, décommentez l'autre et visualiser la différence.
	Il y a trois XSL disponibles, essayez-les tous les trois successivment.
-->  

<!-- <?xml-stylesheet type="text/css" href="library.css" ?>  -->
<!-- <?xml-stylesheet type="text/xsl" href="biblio.xsl"?> -->
<?xml-stylesheet type="text/xsl" href="exo03_c.xsl"?>
<!-- <?xml-stylesheet type="text/xsl" href="exo03_b.xsl"?> -->
<!-- <?xml-stylesheet type="text/xsl" href="exo03_c.xsl"?> -->

<biblio> 
	<livre livre_id="_001">
		<!-- premier élément de type livre -->
		<titre>Les Misérables</titre>
		<auteur>Victor Hugo</auteur>
		<nb_tomes value="3"/>
	</livre>  
		<livre livre_id="_002" type="roman">
		<!-- 2e élément  de type livre-->
		<titre>L'Assomoir</titre>
		<auteur>Émile Zola</auteur>
	</livre> 
	<livre livre_id="_003" lang="en" type="roman">
		<!-- 3e élément de type livre-->
		<titre>David Copperfield</titre>
		<auteur country="GB">Charles Dickens</auteur>
		<auteur country="GB">Ellen Ternan</auteur>
		<nb_tomes value="2"/>
	</livre>
	<livre livre_id="_004" type="roman" lang="nl">
		<!-- 4e élément de type livre-->
		<titre>Gisbrecht van Aemstel</titre>
		<auteur country="NL">Joost van den Vondel</auteur>
	</livre>
</biblio>

=== AlainWafflard/4IPW3/syllabus/25_intégration_XML/library+dtd.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE biblio SYSTEM "library.dtd">
<biblio> 
  <livre livre_id="_001">
    <!-- premier élément de type livre -->
    <titre>Les Misérables</titre>
    <auteur>Victor Hugo</auteur>
    <nb_tomes value="3"/>
  </livre>  
  <livre livre_id="_002" type="roman">
    <titre>L'Assomoir</titre>
    <auteur>Émile Zola</auteur>
  </livre> 
  <livre livre_id="_003" lang="en" type="roman">
    <titre>David Copperfield</titre>
    <auteur country="GB">Charles Dickens</auteur>
    <auteur country="GB">le fils de Charles Dickens</auteur>
    <nb_tomes value="2"/>
  </livre>
</biblio>
